// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://squhwznzheekmktplxus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxdWh3em56aGVla21rdHBseHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MzUxMzEsImV4cCI6MjA1MzQxMTEzMX0.6dvksqFaE6bOSzTiPJqzwO6SLr50kcoy7oZluWcxnyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);